openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/skivsoft/FB2Library/1.0.0
  - description: Demo
    url: https://books.toadstool.online/api/v1
info:
  description: Fb2 books store
  version: "1.0.0"
  title: Fb2 books store
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: info
    description: Library meta information
  - name: admins
    description: Secured Admin-only calls
  - name: developers
    description: Operations available to regular developers
paths:
  /info:
    get:
      tags:
        - info
      summary: Get library meta information
      operationId: getInfo
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Info'
components:
  schemas:
    Info:
      description: Information about the library
      type: object
      properties:
        version:
          type: string
          description: Library version
          example: "20190305"
        authorsCount:
          type: integer
          description: Total number of authors
          example: 100410
        booksCount:
          type: integer
          description: Total number of books
          example: 348738
        usersCount:
          type: integer
          description: Number of registered users
          example: 1000
      required:
        - version
        - authorsCount
        - booksCount
        - usersCount